name: Publish Package

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify your Python version

    - name: Install dependencies
      run: pip install --upgrade setuptools wheel twine

    - name: Run publish script
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        if [ -d "dist" ]; then rm -rf dist; fi
        if [ -d "build" ]; then rm -rf build; fi
        if [ -d "centerer.egg-info" ]; then rm -rf centerer.egg-info; fi
        python setup.py sdist bdist_wheel
        twine upload dist/*